### ISSUE TITLE
YOU CANT PLAY VIDEOS ON WII 

### ISSUE THREAD

**Issue by guest123guest** [TheMrIron2/steamed-hams-channel#6]

**Comment by guest123guest** [comment]
[www.ihateyou.com](url)

**Comment by TheMrIron2** [comment]
This is so ignorant it's not even worth justifying with a proper response, the Photo Channel can play AVI video and programs like WiiMC can play MP4 videos.

**Comment by guest123guest** [comment]
but you need homebrew to do that

**Comment by TheMrIron2** [comment]
This is a homebrew program.

**Comment by BKCrimson** [comment]
Destruction 100
